function parseScannedValue(raw){try{const u=new URL(raw),s=u.searchParams.get("sku");if(s)return s.toUpperCase()}catch(_){}return String(raw||"").trim().toUpperCase()}
function renderSaleLookup(){const sku=$("#saleSku").value.trim();if(sku)lookupSaleSku();else $("#saleProductCard").innerHTML=`<div class="empty">Leia o QR ou digite o SKU.</div>`}
function lookupSaleSku(){const sku=parseScannedValue($("#saleSku").value);$("#saleSku").value=sku;const p=state.products.find(x=>String(x.sku).toUpperCase()===sku);state.currentSaleProduct=p||null;if(!p){$("#saleProductCard").innerHTML=sku?`<div class="panel"><strong>SKU não encontrado.</strong><div class="meta">${esc(sku)}</div></div>`:"";return}const rate=p.mode==="consignado"?commissionRate(p.price):0;$("#saleProductCard").innerHTML=`<div class="sale-card"><h2>${esc(p.name)}</h2><div class="meta">${esc(p.sku)} • ${esc(p.owner)} • ${esc(p.size||"Sem tamanho")}</div><div class="sale-grid"><div><span>Preço</span><strong>${money(p.price)}</strong></div><div><span>Estoque</span><strong>${p.qty}</strong></div><div><span>Modalidade</span><strong>${p.mode==="consignado"?"Consignado":"Próprio"}</strong></div><div><span>Comissão</span><strong>${p.mode==="consignado"?`${Math.round(rate*100)}%`:"—"}</strong></div></div><div class="two"><label>Quantidade<input id="saleQty" class="input" type="number" min="1" max="${p.qty}" value="1"></label><label>Preço unitário<input id="salePrice" class="input" type="number" min="0.01" step="0.01" value="${Number(p.price).toFixed(2)}"></label></div><div class="two"><label>Pagamento<select id="salePayment" class="input"><option>Pix</option><option>Dinheiro</option><option>Cartão débito</option><option>Cartão crédito</option><option>Transferência</option><option>Outro</option></select></label><label>Canal<select id="saleChannel" class="input"><option>Loja física</option><option>Instagram</option><option>WhatsApp</option><option>Indicação</option><option>Outro</option></select></label></div><button class="primary wide" onclick="confirmSale()">Confirmar venda</button></div>`}
window.confirmSale=async function(){const p=state.currentSaleProduct;if(!p)return;const qty=Number($("#saleQty").value),unit=Number($("#salePrice").value);if(qty<1||qty>p.qty){toast("Quantidade sem estoque disponível.");return}if(unit<=0){toast("Preço inválido.");return}const total=qty*unit,rate=p.mode==="consignado"?commissionRate(unit):0,commission=p.mode==="consignado"?total*rate:0,repasse=p.mode==="consignado"?total-commission:0,costTotal=p.mode==="proprio"?qty*Number(p.cost||0):0,result=p.mode==="proprio"?total-costTotal:commission,sale={id:uid("ven"),date:nowISO(),sku:p.sku,productId:p.id,productName:p.name,qty,unitPrice:unit,total,commissionRate:rate,commission,repasse,mode:p.mode,owner:p.owner,ownerPhone:p.ownerPhone||"",payment:$("#salePayment").value,channel:$("#saleChannel").value,receivedStatus:"Recebido",repasseStatus:p.mode==="consignado"?"Pendente":"Não aplicável",costTotal,result};p.qty-=qty;p.updatedAt=nowISO();await dbPut("products",p);await dbPut("sales",sale);await loadState();state.currentSaleProduct=null;$("#saleSku").value="";$("#saleProductCard").innerHTML="";toast(`Venda registrada: ${money(total)}`);nav("dashboard")};

function qrGroupSvg(payload,x,y,module=6){const m=TudoTalQR.makeMatrix(payload),total=(21+8)*module;let s=`<rect x="${x}" y="${y}" width="${total}" height="${total}" fill="#fff"/><g fill="#000" shape-rendering="crispEdges">`;for(let yy=0;yy<m.length;yy++)for(let xx=0;xx<m.length;xx++)if(m[yy][xx])s+=`<rect x="${x+(xx+4)*module}" y="${y+(yy+4)*module}" width="${module}" height="${module}"/>`;return s+"</g>"}
function labelSvg(p){if(!p)return"";const qr=qrGroupSvg(p.sku,218,33,6),safeName=esc(p.name).slice(0,28),safeSize=esc(p.size||"-"),safeSku=esc(p.sku);return`<svg xmlns="http://www.w3.org/2000/svg" width="50mm" height="30mm" viewBox="0 0 400 240" shape-rendering="crispEdges"><rect width="400" height="240" fill="#fff"/><text x="18" y="36" font-family="Georgia,serif" font-size="26" font-weight="700">Tudo &amp; Tal</text><text x="19" y="53" font-family="Arial,sans-serif" font-size="10" letter-spacing="2.5">BRECHÓ</text><text x="18" y="96" font-family="Arial,sans-serif" font-size="22" font-weight="700">${safeName}</text><text x="18" y="128" font-family="Arial,sans-serif" font-size="18">Tam.: ${safeSize}</text><text x="18" y="170" font-family="Arial,sans-serif" font-size="30" font-weight="700">${money(p.price)}</text><text x="18" y="211" font-family="Arial,sans-serif" font-size="16" font-weight="700">${safeSku}</text>${qr}</svg>`}
function renderLabelOptions(){const sel=$("#labelProduct"),current=sel.value;sel.innerHTML=[...state.products].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")).map(p=>`<option value="${p.id}">${esc(p.name)} — ${esc(p.sku)}</option>`).join("");if(current&&state.products.some(p=>p.id===current))sel.value=current;renderLabel()}
function renderLabel(){const p=state.products.find(x=>x.id===$("#labelProduct").value)||state.products[0];$("#labelPreview").innerHTML=labelSvg(p)}
function printLabel(){window.print()}

function drawQrCanvas(ctx,payload,x,y,module=6){const m=TudoTalQR.makeMatrix(payload),total=(21+8)*module;ctx.fillStyle="#fff";ctx.fillRect(x,y,total,total);ctx.fillStyle="#000";for(let yy=0;yy<m.length;yy++)for(let xx=0;xx<m.length;xx++)if(m[yy][xx])ctx.fillRect(x+(xx+4)*module,y+(yy+4)*module,module,module)}
function downloadLabel(){const p=state.products.find(x=>x.id===$("#labelProduct").value)||state.products[0];if(!p)return;const c=document.createElement("canvas");c.width=400;c.height=240;const ctx=c.getContext("2d");ctx.imageSmoothingEnabled=false;ctx.fillStyle="#fff";ctx.fillRect(0,0,400,240);ctx.fillStyle="#111";ctx.font="700 26px Georgia";ctx.fillText("Tudo & Tal",18,36);ctx.font="700 10px Arial";ctx.fillText("B R E C H Ó",19,53);ctx.font="700 22px Arial";ctx.fillText(String(p.name||"").slice(0,28),18,96);ctx.font="18px Arial";ctx.fillText("Tam.: "+(p.size||"-"),18,128);ctx.font="700 30px Arial";ctx.fillText(money(p.price),18,170);ctx.font="700 16px Arial";ctx.fillText(p.sku,18,211);drawQrCanvas(ctx,p.sku,218,33,6);c.toBlob(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`Etiqueta_${p.sku}_50x30_PT260.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)},"image/png",1)}