(function(global){
"use strict";
const SIZE=21,DATA_CODEWORDS=16,ECC_CODEWORDS=10,RS_GEN=[216,194,159,111,199,94,95,113,157,193];
function gfMul(x,y){let z=0;for(let i=0;i<8;i++){if(y&1)z^=x;const hi=x&0x80;x=(x<<1)&255;if(hi)x^=0x1D;y>>>=1}return z}
function appendBits(a,v,l){for(let i=l-1;i>=0;i--)a.push((v>>>i)&1)}
function makeDataCodewords(text){const bytes=Array.from(new TextEncoder().encode(text));if(bytes.length>14)throw new Error("QR V1-M suporta até 14 bytes.");const bits=[];appendBits(bits,4,4);appendBits(bits,bytes.length,8);bytes.forEach(b=>appendBits(bits,b,8));const cap=DATA_CODEWORDS*8;appendBits(bits,0,Math.min(4,cap-bits.length));while(bits.length%8)bits.push(0);const out=[];for(let i=0;i<bits.length;i+=8){let v=0;for(let j=0;j<8;j++)v=(v<<1)|bits[i+j];out.push(v)}let pad=0;while(out.length<DATA_CODEWORDS)out.push(pad++%2===0?0xEC:0x11);return out}
function makeEcc(data){const rem=new Array(ECC_CODEWORDS).fill(0);for(const b of data){const factor=b^rem[0];rem.shift();rem.push(0);for(let i=0;i<ECC_CODEWORDS;i++)rem[i]^=gfMul(RS_GEN[i],factor)}return rem}
function setFunc(mod,fun,x,y,val){if(x<0||y<0||x>=SIZE||y>=SIZE)return;mod[y][x]=!!val;fun[y][x]=true}
function drawFinder(mod,fun,cx,cy){for(let dy=-4;dy<=4;dy++)for(let dx=-4;dx<=4;dx++){const x=cx+dx,y=cy+dy;if(x<0||y<0||x>=SIZE||y>=SIZE)continue;const d=Math.max(Math.abs(dx),Math.abs(dy));setFunc(mod,fun,x,y,d!==2&&d!==4)}}
function calcFormatBits(mask){const data=mask;let rem=data;for(let i=0;i<10;i++)rem=(rem<<1)^(((rem>>>9)&1)?0x537:0);return((data<<10)|rem)^0x5412}
function drawFormat(mod,fun,mask){const bits=calcFormatBits(mask),bit=i=>((bits>>>i)&1)!==0;for(let i=0;i<=5;i++)setFunc(mod,fun,8,i,bit(i));setFunc(mod,fun,8,7,bit(6));setFunc(mod,fun,8,8,bit(7));setFunc(mod,fun,7,8,bit(8));for(let i=9;i<15;i++)setFunc(mod,fun,14-i,8,bit(i));for(let i=0;i<8;i++)setFunc(mod,fun,SIZE-1-i,8,bit(i));for(let i=8;i<15;i++)setFunc(mod,fun,8,SIZE-15+i,bit(i));setFunc(mod,fun,8,SIZE-8,true)}
function maskBit(m,x,y){switch(m){case 0:return((x+y)&1)===0;case 1:return(y&1)===0;case 2:return x%3===0;case 3:return(x+y)%3===0;case 4:return((Math.floor(y/2)+Math.floor(x/3))&1)===0;case 5:return(x*y)%2+(x*y)%3===0;case 6:return(((x*y)%2+(x*y)%3)&1)===0;case 7:return((((x+y)%2)+((x*y)%3))&1)===0;default:return false}}
function penalty(mod){let score=0;for(let y=0;y<SIZE;y++){let c=mod[y][0],run=1;for(let x=1;x<SIZE;x++){if(mod[y][x]===c){run++;if(run===5)score+=3;else if(run>5)score++}else{c=mod[y][x];run=1}}}for(let x=0;x<SIZE;x++){let c=mod[0][x],run=1;for(let y=1;y<SIZE;y++){if(mod[y][x]===c){run++;if(run===5)score+=3;else if(run>5)score++}else{c=mod[y][x];run=1}}}for(let y=0;y<SIZE-1;y++)for(let x=0;x<SIZE-1;x++){const c=mod[y][x];if(c===mod[y][x+1]&&c===mod[y+1][x]&&c===mod[y+1][x+1])score+=3}let dark=0;for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++)if(mod[y][x])dark++;score+=Math.floor(Math.abs(dark*20-SIZE*SIZE*10)/(SIZE*SIZE))*10;return score}
function buildWithMask(codewords,mask){const mod=Array.from({length:SIZE},()=>Array(SIZE).fill(false)),fun=Array.from({length:SIZE},()=>Array(SIZE).fill(false));drawFinder(mod,fun,3,3);drawFinder(mod,fun,SIZE-4,3);drawFinder(mod,fun,3,SIZE-4);for(let i=8;i<SIZE-8;i++){setFunc(mod,fun,6,i,i%2===0);setFunc(mod,fun,i,6,i%2===0)}drawFormat(mod,fun,mask);const dataBits=[];codewords.forEach(b=>appendBits(dataBits,b,8));let idx=0;for(let right=SIZE-1;right>=1;right-=2){if(right===6)right--;const up=(((right+1)&2)===0);for(let vert=0;vert<SIZE;vert++){const y=up?SIZE-1-vert:vert;for(let j=0;j<2;j++){const x=right-j;if(!fun[y][x]&&idx<dataBits.length){let val=dataBits[idx++]!==0;if(maskBit(mask,x,y))val=!val;mod[y][x]=val}}}}return mod}
function makeMatrix(text){const data=makeDataCodewords(text),codewords=data.concat(makeEcc(data));let best=null,bestScore=Infinity;for(let mask=0;mask<8;mask++){const m=buildWithMask(codewords,mask),s=penalty(m);if(s<bestScore){bestScore=s;best=m}}return best}
global.TudoTalQR={makeMatrix,size:SIZE};
})(typeof window!=="undefined"?window:globalThis);